name: Dowith Frontend Auto Deploy to EC2

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2
  CODE_DEPLOY_APPLICATION_NAME: dowith-front-code-deploy-application
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: dowith-front-code-deploy-group

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19.8.1'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to CodeDeploy from GitHub
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
            --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}